# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-26 19:48
from __future__ import unicode_literals

import clickerApp.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CheckboxInput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkbox_input_title', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'checkbox_input',
            },
        ),
        migrations.CreateModel(
            name='RadioInput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('radio_input_title', models.CharField(blank=True, max_length=300)),
            ],
            options={
                'db_table': 'radio_input',
            },
        ),
        migrations.CreateModel(
            name='RadioInputVariant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('radio_input_variant_title', models.CharField(blank=True, max_length=300)),
                ('radio_input_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clickerApp.RadioInput')),
            ],
            options={
                'db_table': 'radio_input_variant',
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_title', models.CharField(max_length=200)),
                ('add_title_to_comment', models.BooleanField(default=False)),
                ('move_title', models.CharField(max_length=300)),
                ('move_description', models.TextField(blank=True, max_length=2000)),
                ('seq', models.PositiveIntegerField(default=0)),
                ('path', clickerApp.models.TreeOrderField(blank=True, max_length=255)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_set', to='clickerApp.State')),
            ],
            options={
                'db_table': 'state',
            },
        ),
        migrations.CreateModel(
            name='TextInput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_input_title', models.CharField(blank=True, max_length=300)),
                ('text_input_max_width', models.IntegerField()),
                ('text_input_after', models.CharField(blank=True, max_length=300)),
                ('state_input_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clickerApp.State')),
            ],
            options={
                'db_table': 'text_input',
            },
        ),
        migrations.CreateModel(
            name='Tip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tip_title', models.CharField(max_length=300)),
                ('tip_description', models.TextField(blank=True, max_length=2000)),
                ('state_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clickerApp.State')),
            ],
            options={
                'db_table': 'tip',
            },
        ),
        migrations.AddField(
            model_name='radioinput',
            name='state_input_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clickerApp.State'),
        ),
        migrations.AddField(
            model_name='checkboxinput',
            name='state_input_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clickerApp.State'),
        ),
    ]
