# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-23 22:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clickerApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_set', to='clickerApp.State'),
        ),
    ]
