# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-26 20:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clickerApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='testChar',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
