# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-29 23:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clickerApp', '0005_state_hidden_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='StateUserNotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_body', models.TextField(blank=True, default=b'')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clickerApp.State')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '\u0417\u0430\u043c\u0435\u0442\u043a\u0430 \u043f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u0435\u043b\u044f \u043a \u0448\u0430\u0433\u0443 \u0434\u0438\u0430\u0433\u043d\u043e\u0441\u0442\u0438\u043a\u0438',
                'verbose_name_plural': '\u0417\u0430\u043c\u0435\u0442\u043a\u0438 \u043f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u0435\u043b\u0435 \u043a \u0448\u0430\u0433\u0430\u043c \u0434\u0438\u0430\u0433\u043d\u043e\u0441\u0442\u0438\u043a\u0438',
            },
        ),
    ]
