# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-01 19:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clickerApp', '0007_globalusernotes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state',
            name='path',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
