# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-04 05:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fileUpload', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'verbose_name': '\u0424\u0430\u0439\u043b', 'verbose_name_plural': '\u0424\u0430\u0439\u043b\u044b'},
        ),
    ]
