# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-25 18:52
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drive', '0002_auto_20160304_0804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drivelist',
            name='drive_date',
            field=models.DateField(default=datetime.date(2016, 4, 25)),
        ),
    ]
