# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-23 01:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drive', '0004_auto_20160522_0415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drivetime',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
